### ISSUE TITLE
/admin broken : missing javascript / css / js.io files for 

### ISSUE THREAD

**Issue by ashokrkm** [play-co/hookbox#9]
1. none of the jquery ui/js files are installed
   http://pastie.org/930208
2. js.io files are not included in the repo
   there is a symlink to /home/mcarter for js.io files, and /admin users js.io . but js.io is not included in the repo

**Comment by mcarter** [comment]
fixed in 8ae9fda

**Comment by ashokrkm** [comment]
still not fixed, jquery css and js files are not getting installed correctly.

**Comment by mcarter** [comment]
does this only happen when you do setup.py install, or does it also happen when you do setup.py develop?

**Comment by ashokrkm** [comment]
it happens when I do setup.py install.

**Comment by ashokrkm** [comment]
I have not tried setup.py develop
